# Generated by Django 4.1.3 on 2022-11-13 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted ?')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is archived ?')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=64, null=True, verbose_name='Description ')),
                ('remind_at', models.DateTimeField(verbose_name='Reminde_at')),
                ('repeat', models.IntegerField(choices=[(0, 'Dont Reapeat'), (1, 'Reapeat Hour Before'), (2, 'Reapeat Day Before'), (3, 'Reapeat Week Before'), (4, 'Reapea Month Before')], default=0, verbose_name='How Repeat ?')),
                ('notification_status', models.IntegerField(choices=[(0, 'None'), (1, 'Failed'), (2, 'Success')], default=0, verbose_name='Notification Status ?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': ' Reminder',
                'verbose_name_plural': ' Reminder',
            },
        ),
    ]
